analyzer:
  exclude:
    - "lib/**.g.dart"
    - "lib/**.freezed.dart"
    - "lib/**.config.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - "test/**.mocks.dart"
