name: wishey
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.2
  bloc: ^8.0.2

  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  logger: ^1.1.0

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  bloc_test: ^9.0.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  hive_generator: ^1.1.2
  injectable_generator: ^1.5.2
  mockito: ^5.0.17
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
